name: ci
on: 
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkour sources
              uses: actions/checkout@v2
            
            - name: Setup mdBook
              uses: peaceiris/actions-mdbook@v1
              with:
                mdbook-version: 'latest'
            
            - name: Build docs
              run: |
                mdbook build
            
            - name: Deploy
              uses: eaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./book